### ISSUE TITLE
TypeScript as a peerDependency

### ISSUE THREAD

**Issue by ghost** [ajafff/tsutils#134]
Are there any reasons this package has so old TypeScript peerDependency? It breaks the build:

```
 ERROR  @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree: tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
```

**Comment by ajafff** [comment]
This package has a peerDependency on TypeScript, because it depends on TypeScript being present, but you need to bring your own version of it. (just in case someone reading this doesn't know what a peer dependency is)
It allows any stable version starting from `2.8.0`. the rest is there because removing it is a breaking change and there's no need to remove support for old nightly builds.

If you have TypeScript installed and your package manager complains about unmatched version, your package manager is broken.

If you don't have TypeScript installed, why would you install this package? Its sole purpose is to simplify using the TypeScript API.

**Comment by ghost** [comment]
@ajafff I'm using TypeScript but its version much newer than you specified in its peerDependencies, hence it does not satisfy the semver.

Please, refer to semantic versioning doc and see that TypeScript v4 does not satisfy your >= v3 condition. The issue is still open.

**Comment by ghost** [comment]
If you don't care about its version, just make it `"typescript": "*"`

**Comment by ghost** [comment]
> If you have TypeScript installed and your package manager complains about unmatched version, your package manager is broken.

cc @zkochan

**Comment by zkochan** [comment]
You probably use `strict-peer-dependencies`

pnpm is not broken. If the typescript version does not match the range specified in peer dependencies and `strict-peer-dependencies` is set to `true`, then pnpm will exit with an error.

This might cause an error on npm v7 as well.

**Comment by ghost** [comment]
> You probably use strict-peer-dependencies

Yes, I prefer fixing warnings, not ignoring them. I have a TypeScript v4 and when configuring typescript-eslint it complain about this package not having it in peerDependency.

**Comment by ajafff** [comment]
> pnpm is not broken. If the typescript version does not match the range specified in peer dependencies

has anyone taken the time to investigate why typescript@4 would not satisfy `>= 2.8.0`? I consider that broken behavior

**Comment by ghost** [comment]
@ajafff we are considering any option, yes. There are more tools involved, and it is hard to find the culprit.

I checked the semver range here (https://semver.npmjs.com) and I can see that `4.2.4` is satisfied by `>= 2.8.0`. So it is indeed a strange error not related to this package.

**Comment by darekkay** [comment]
> If you don't have TypeScript installed, why would you install this package? Its sole purpose is to simplify using the TypeScript API.

@ajafff One use case: having an eslint-config package that supports different environments conditionally, like JavaScript projects (no TS required) and TypeScript projects at the same time ([example](https://github.com/darekkay/darekkay-eslint-config/)). This currently leads to a warning because of `tsutils` being included in packages like `@typescript-eslint/eslint-plugin`:

```
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >=
3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".

```

People keep having this issue because of `tsutils`, unfortunately:

- https://github.com/typescript-eslint/typescript-eslint/issues/1287
- https://github.com/jest-community/eslint-plugin-jest/issues/467

This is what [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json/#peerdependenciesmeta) was created for:

> This allows you to integrate and interact with a variety of host packages without requiring all of them to be installed.

This would be the required change in `package.json`:

```
  "peerDependenciesMeta": {
    "typescript": {
      "optional": true
    }
  }
```

Are you open to such a change?

**Comment by silverwind** [comment]
I too came here through a eslint plugin which through a chain of dependencies and with npm v7 now installing `peerDependencies`, ends up bloating my `node_modules` with an unused typescript compiler:

```
eslint-plugin-jest@24.3.6
┬ @typescript-eslint/experimental-utils@4.24.0
└─┬ @typescript-eslint/typescript-estree@4.24.0
  └─┬ tsutils@3.21.0
    └── typescript@4.2.4
```
