### ISSUE TITLE
API to get variable usage include global var

### ISSUE THREAD

**Issue by xiaoxiangmoe** [ajafff/tsutils#87]
`collectVariableUsage`  only collect variable with variable declaration.

Can we get global variable usage such as `process.env.REACT_APP_HOST`'s `process` or `window.document`'s `window`?

**Comment by xiaoxiangmoe** [comment]
Emmm, I think it is okay that I don't track changes in global variables in react-hooks.

**Comment by ajafff** [comment]
`collectVariableUsage` only works for identifiers (variables, parameters, classes, interfaces, ...) declared in the current file. It also doesn't find uses in other files. On a related note: `collectVariableUsage` has some bugs that will be fixed in the new implementation in #84.

If I understand your request correctly, you want to analyze the whole project. That's possible using Typescript's LanguageService (the name of the API is ReferenceFinder, findReferences, findAllReferences or something similar IIRC).
There's also https://github.com/dsherret/ts-simple-ast which uses the LanguageService behind the scenes and provides a simple API on top of it.
