### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by haggholm** [ajafff/tsutils#88]
In some projects, I conditionally use [longjohn](https://www.npmjs.com/package/longjohn) when `NODE_ENV !== 'production'`. This turns out to break some import/dependency checks I am implementing using `tsutils`.

Source (yes, that’s it):

```javascript
require('longjohn');
```

Result:

```bash
TypeError: Cannot read property 'kind' of undefined
    at ImportFinder._findNestedImports (/home/petter/owl/client/devtools/node_modules/tsutils/util/util.js:1070:30)
    at ImportFinder.find (/home/petter/owl/client/devtools/node_modules/tsutils/util/util.js:1016:18)
    at findImportLikeNodes (/home/petter/owl/client/devtools/node_modules/tsutils/util/util.js:1001:48)
    at Object.findImports (/home/petter/owl/client/devtools/node_modules/tsutils/util/util.js:971:24)
    at p.getSourceFiles.filter.forEach (/home/petter/lint_cmds/depcheck.js:50:6)
```

The relevant part of the lint command:

```javascript
const ts = require('typescript');
const p = ts.createProgram(
	tsFiles, // array of paths
	JSON.parse(fs.readFileSync('tsconfig.json', 'utf8'))
);
p.getSourceFiles().forEach((f) => tsutils.findImports(f, 1 | 2 | 16 | 32));
```

**Comment by ajafff** [comment]
Almost all functions exported from this library expect `parent` references of nodes to be set.
In your case you just create the Program but don't set parent pointers. That's why it crashes on every `require()` or `import()` (this was introduced as part of a rather recent optimization).

How to set parent pointers:

* implicitly by binding the Program: `p.getTypeChecker()`
* creating a CompilerHost that sets parent pointers on each SourceFile (3rd parameter to `ts.createProgram`): `ts.createCompilerHost(compilerOptions, /*setParentNodex*/ true)`

---

On a related note: you shouldn't parse compilerOptions with `JSON.parse` because TypeScript expects normalized values. Prefer `ts.readConfigFile` and `ts.parseJsonConfigFileContent`.

**Comment by haggholm** [comment]
I see. Well, sort of… At any rate, it works now; so thank you for the help!
